services:
  db:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata

volumes:
  pg_data: